### ISSUE TITLE
Filter out DONE and archived items

### ISSUE THREAD

**Issue by bhipple** [unhammer/org-mru-clock#9]
When I'm clocking in, it's unlikely that I want to clock into a task that's in a completed state.  I started looking into refactoring to allow us to install a list of predicate filter functions, but figured I'd open an issue in case you've already looked at implementing something like this.

**Comment by unhammer** [comment]
I haven't, that sounds like a good idea :) It might be simpler to just make it one function, like how `org-agenda-skip-function` does it, and then the user can combine (manually or with fancy [combinators](https://github.com/magnars/dash.el/blob/master/dash-functional.el#L110)) several into one (then the user gets the freedom to choose if they want all criteria to match, or at least one, or something more complicated).

**Comment by unhammer** [comment]
@bhipple does https://github.com/unhammer/org-mru-clock/tree/predicate seem like it would solve it? Note the Limitations – maybe there's a better way I haven't thought of?

**Comment by bhipple** [comment]
Nice!  This is successfully filtering out DONE items, but my archived items are still showing up; if I get time I'll dig into it later today, but it looks like you've done all the heavy lifting; thanks! :clinking_glasses:

**Comment by unhammer** [comment]
Oh, I was just excluding those *tagged* as archived, not archived to other files. 

Unfortunately I can't find anything in org-mode that tells me that a file is an archive file (it's easy to go from non-archive to archive file path, but not the other way), and since `org-archive-location` is customizable I can't think of a non-hacky solution that works for everyone. But you could add `(not (string-suffix-p "_archive" (buffer-file-name)))` in your `org-mru-clock-predicate`.

But: I also added a new defcustom for changing what files we search for clocks in, which should be faster (archive files can get huge!). So if you only ever clock in to tasks in `org-agenda-files`, just `(setq org-mru-clock-files #'org-agenda-files)`, or if you just want to do all `org-files-list` except the ones ending in _archive `(setq org-mru-clock-files (lambda () (cl-remove-if (lambda (f) (string-suffix-p "_archive" f)) (org-files-list))))`

**Comment by bhipple** [comment]
Both of your proposed solutions on the `org-mru-clock-files` work perfectly for me on the `predicate` branch.  Since I happen to only clock into agenda files, I'm going with the simpler first one.  This is really great, thank you!

**Comment by unhammer** [comment]
Closed in c89f501..a816e17
